require("mauwuro.plugins-setup")

require("mauwuro.core.options")
require("mauwuro.core.keymaps")
require("mauwuro.core.colorscheme")

require("mauwuro.plugins.comment")
require("mauwuro.plugins.nvim-tree")
require("mauwuro.plugins.lualine")
require("mauwuro.plugins.todo-comments")
require("mauwuro.plugins.which-key")
require("mauwuro.plugins.telescope")
require("mauwuro.plugins.nvim-cmp")
require("mauwuro.plugins.autopairs")
require("mauwuro.plugins.treesitter")
require("mauwuro.plugins.gitsigns")
require("mauwuro.plugins.neogit")

require("mauwuro.plugins.lsp.mason")
require("mauwuro.plugins.lsp.lspsaga")
require("mauwuro.plugins.lsp.lspconfig")
require("mauwuro.plugins.lsp.conform")
require("mauwuro.plugins.dap.dapconfig")
require("mauwuro.plugins.dap.dapui")
require("mauwuro.plugins.dap.dapkeybindings")
